CREATE SEQUENCE felhasznalo_seq START WITH 100;
CREATE SEQUENCE jegyzetek_seq START WITH 100;
CREATE SEQUENCE vasarlasok_seq START WITH 100;
CREATE SEQUENCE egytemek_seq START WITH 100;
CREATE SEQUENCE error_log_seq START WITH 100;
